### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ylin00** [jmfrancklab/pyspecdata#1]
Environment: OSX 10.15, Python2.7

Run: `from pyspecdata import fornotebook`

Error: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/pyspecdata/fornotebook.py", line 17, in <module>
    from tables import openFile
ImportError: cannot import name openFile

**Comment by ylin00** [comment]
pytables changed API from 2.X to 3.X. 

http://www.pytables.org/MIGRATING_TO_3.x.html?highlight=openfiles
